// Gli elementi del pannello, cercati per id una volta sola e restituiti in un oggetto.
//
// Perche' gli aiutanti qui sotto (2026-09-20): `document.getElementById` dichiara
// `HTMLElement`, che non ha `.value`, `.checked`, `.min`. Ogni cursore letto o scritto
// da live-controls.js e control-panel.js era un errore di tipo: 354 su 524, il 68% del
// debito misurato il 2026-09-19. Si corregge in un posto solo, quello che sa che cosa
// c'e' dietro ogni id. Quale aiutante per quale chiave l'ho deciso guardando il tag
// vero (index.html e fixed-control-defaults.js: 242 <input>, 20 <select>, 7 <button>,
// il resto <output>/<span>/<div>) e incrociandolo con la proprieta' che il codice usa
// su ogni chiave: nessun incrocio sbagliato. Niente `any`: farebbe sparire gli errori
// veri insieme a quelli falsi, ed e' gia' successo (vedi README, trappola 1).

/** @param {string} id */
const cursore = (id) => /** @type {HTMLInputElement} */ (document.getElementById(id));
/** @param {string} id */
const scelta = (id) => /** @type {HTMLSelectElement} */ (document.getElementById(id));
/** @param {string} id */
const bottone = (id) => /** @type {HTMLButtonElement} */ (document.getElementById(id));
/** Etichette di lettura (<output>, <span>) e contenitori: si scrive .textContent, basta HTMLElement. @param {string} id */
const etichetta = (id) => document.getElementById(id);

export function createControlEls() {
  return {
  hexOffset: cursore('hex-offset'),
  hexOffsetVal: etichetta('hex-offset-val'),
  hexRadius: cursore('hex-radius'),
  hexRadiusVal: etichetta('hex-radius-val'),
  hexDropDelay: cursore('hex-drop-delay'),
  hexDropDelayVal: etichetta('hex-drop-delay-val'),
  hexDropSpeed: cursore('hex-drop-speed'),
  hexDropSpeedVal: etichetta('hex-drop-speed-val'),
  hexRecovery: cursore('hex-recovery'),
  hexRecoveryVal: etichetta('hex-recovery-val'),
  tileHeight: cursore('tile-height'),
  tileHeightVal: etichetta('tile-height-val'),
  tileScale: cursore('tile-scale'),
  tileScaleVal: etichetta('tile-scale-val'),
  hexGap: cursore('hex-gap'),
  hexGapVal: etichetta('hex-gap-val'),
  tileHitLight: cursore('tile-hit-light'),
  tileHitLightVal: etichetta('tile-hit-light-val'),
  playerTileLight: cursore('player-tile-light'),
  playerTileLightVal: etichetta('player-tile-light-val'),
  roadNormal: cursore('road-normal'),
  roadNormalVal: etichetta('road-normal-val'),
  ambientLight: cursore('ambient-light'),
  ambientVal: etichetta('ambient-val'),
  keyLight: cursore('key-light'),
  keyVal: etichetta('key-val'),
  exposure: cursore('exposure'),
  exposureVal: etichetta('exposure-val'),
  skyChoice: scelta('sky-choice'),
  skyQuality: scelta('sky-quality'),
  skyBrightness: cursore('sky-brightness'),
  skyBrightnessVal: etichetta('sky-brightness-val'),
  skyHue: cursore('sky-hue'),
  skyHueVal: etichetta('sky-hue-val'),
  skyCloudContrast: cursore('sky-cloud-contrast'),
  skyCloudContrastVal: etichetta('sky-cloud-contrast-val'),
  skyStormFrequency: cursore('sky-storm-frequency'),
  skyStormFrequencyVal: etichetta('sky-storm-frequency-val'),
  skyStormIntensity: cursore('sky-storm-intensity'),
  skyStormIntensityVal: etichetta('sky-storm-intensity-val'),
  skyStormSize: cursore('sky-storm-size'),
  skyStormSizeVal: etichetta('sky-storm-size-val'),
  skyStormCloudThreshold: cursore('sky-storm-cloud-threshold'),
  skyStormCloudThresholdVal: etichetta('sky-storm-cloud-threshold-val'),
  skyStormBand: cursore('sky-storm-band'),
  skyStormBandVal: etichetta('sky-storm-band-val'),
  skyStormVeil: cursore('sky-storm-veil'),
  skyStormVeilVal: etichetta('sky-storm-veil-val'),
  boulevardWidthScale: cursore('boulevard-width-scale'),
  boulevardWidthScaleVal: etichetta('boulevard-width-scale-val'),
  roadLight: cursore('road-light'),
  roadLightVal: etichetta('road-light-val'),
  roadReflect: cursore('road-reflect'),
  roadReflectVal: etichetta('road-reflect-val'),
  roadBuildingReflect: cursore('road-building-reflect'),
  roadBuildingReflectVal: etichetta('road-building-reflect-val'),
  roadMetalness: cursore('road-metalness'),
  roadMetalnessVal: etichetta('road-metalness-val'),
  roadRoughness: cursore('road-roughness'),
  roadRoughnessVal: etichetta('road-roughness-val'),
  roadHue: cursore('road-hue'),
  roadHueVal: etichetta('road-hue-val'),
  roadSat: cursore('road-sat'),
  roadSatVal: etichetta('road-sat-val'),
  roadBright: cursore('road-bright'),
  roadBrightVal: etichetta('road-bright-val'),
  roadBoundaryHexEnabled: scelta('road-boundary-hex-enabled'),
  roadBoundaryHexEnabledVal: etichetta('road-boundary-hex-enabled-val'),
  roadBoundaryHexRows: cursore('road-boundary-hex-rows'),
  roadBoundaryHexRowsVal: etichetta('road-boundary-hex-rows-val'),
  roadSideHexExtraRows: cursore('road-side-hex-extra-rows'),
  roadSideHexExtraRowsVal: etichetta('road-side-hex-extra-rows-val'),
  roadBoundaryHexBrightness: cursore('road-boundary-hex-brightness'),
  roadBoundaryHexBrightnessVal: etichetta('road-boundary-hex-brightness-val'),
  roadBoundaryHexOpacity: cursore('road-boundary-hex-opacity'),
  roadBoundaryHexOpacityVal: etichetta('road-boundary-hex-opacity-val'),
  roadBoundaryHexY: cursore('road-boundary-hex-y'),
  roadBoundaryHexYVal: etichetta('road-boundary-hex-y-val'),
  roadBoundaryHexOutset: cursore('road-boundary-hex-outset'),
  roadBoundaryHexOutsetVal: etichetta('road-boundary-hex-outset-val'),
  roadBoundaryRowY: Array.from({ length: 10 }, (_, index) => cursore(`road-boundary-row-${index + 1}-y`)),
  roadBoundaryRowYVal: Array.from({ length: 10 }, (_, index) => etichetta(`road-boundary-row-${index + 1}-y-val`)),
  roadBoundaryCollisionEnabled: scelta('road-boundary-collision-enabled'),
  roadBoundaryCollisionEnabledVal: etichetta('road-boundary-collision-enabled-val'),
  roadBoundaryCollisionMargin: cursore('road-boundary-collision-margin'),
  roadBoundaryCollisionMarginVal: etichetta('road-boundary-collision-margin-val'),
  roadBoundaryCameraLead: cursore('road-boundary-camera-lead'),
  roadBoundaryCameraLeadVal: etichetta('road-boundary-camera-lead-val'),
  roadBoundaryPulseStrength: cursore('road-boundary-pulse-strength'),
  roadBoundaryPulseStrengthVal: etichetta('road-boundary-pulse-strength-val'),
  boundaryErrorVisible: scelta('boundary-error-visible'),
  boundaryErrorVisibleVal: etichetta('boundary-error-visible-val'),
  boundaryErrorSize: cursore('boundary-error-size'),
  boundaryErrorSizeVal: etichetta('boundary-error-size-val'),
  boundaryErrorAnchor: scelta('boundary-error-anchor'),
  boundaryErrorAnchorVal: etichetta('boundary-error-anchor-val'),
  boundaryErrorAnimation: cursore('boundary-error-animation'),
  boundaryErrorAnimationVal: etichetta('boundary-error-animation-val'),
  boundaryErrorDuration: cursore('boundary-error-duration'),
  boundaryErrorDurationVal: etichetta('boundary-error-duration-val'),
  boundaryErrorGlitch: cursore('boundary-error-glitch'),
  boundaryErrorGlitchVal: etichetta('boundary-error-glitch-val'),
  boundaryErrorRenderMode: scelta('boundary-error-render-mode'),
  boundaryErrorRenderModeVal: etichetta('boundary-error-render-mode-val'),
  boundaryErrorFloorLightEnabled: scelta('boundary-error-floor-light-enabled'),
  boundaryErrorFloorLightEnabledVal: etichetta('boundary-error-floor-light-enabled-val'),
  boundaryErrorFloorLightRadius: cursore('boundary-error-floor-light-radius'),
  boundaryErrorFloorLightRadiusVal: etichetta('boundary-error-floor-light-radius-val'),
  boundaryErrorFloorLightIntensity: cursore('boundary-error-floor-light-intensity'),
  boundaryErrorFloorLightIntensityVal: etichetta('boundary-error-floor-light-intensity-val'),
  boundaryErrorFloorLightOpacity: cursore('boundary-error-floor-light-opacity'),
  boundaryErrorFloorLightOpacityVal: etichetta('boundary-error-floor-light-opacity-val'),
  boundaryErrorFloorLightHue: cursore('boundary-error-floor-light-hue'),
  boundaryErrorFloorLightHueVal: etichetta('boundary-error-floor-light-hue-val'),
  boundaryErrorFloorLightY: cursore('boundary-error-floor-light-y'),
  boundaryErrorFloorLightYVal: etichetta('boundary-error-floor-light-y-val'),
  boundaryErrorFloorLightSoftness: cursore('boundary-error-floor-light-softness'),
  boundaryErrorFloorLightSoftnessVal: etichetta('boundary-error-floor-light-softness-val'),
  ledBrightness: cursore('led-brightness'),
  ledBrightnessVal: etichetta('led-brightness-val'),
  ledThickness: cursore('led-thickness'),
  ledThicknessVal: etichetta('led-thickness-val'),
  ledDistance: cursore('led-distance'),
  ledDistanceVal: etichetta('led-distance-val'),
  buildingHorizontalLedDistance: cursore('building-horizontal-led-distance'),
  buildingHorizontalLedDistanceVal: etichetta('building-horizontal-led-distance-val'),
  buildingHorizontalLedThickness: cursore('building-horizontal-led-thickness'),
  buildingHorizontalLedThicknessVal: etichetta('building-horizontal-led-thickness-val'),
  buildingHorizontalLedRadius: cursore('building-horizontal-led-radius'),
  buildingHorizontalLedRadiusVal: etichetta('building-horizontal-led-radius-val'),
  ledHue: cursore('led-hue'),
  ledHueVal: etichetta('led-hue-val'),
  basePadLedBrightness: cursore('base-pad-led-brightness'),
  basePadLedBrightnessVal: etichetta('base-pad-led-brightness-val'),
  basePadLedThickness: cursore('base-pad-led-thickness'),
  basePadLedThicknessVal: etichetta('base-pad-led-thickness-val'),
  basePadLedOffset: cursore('base-pad-led-offset'),
  basePadLedOffsetVal: etichetta('base-pad-led-offset-val'),
  basePadLedHue: cursore('base-pad-led-hue'),
  basePadLedHueVal: etichetta('base-pad-led-hue-val'),
  basePadGlobalY: cursore('base-pad-global-y'),
  basePadGlobalYVal: etichetta('base-pad-global-y-val'),
  basePadCurbEnabled: scelta('base-pad-curb-enabled'),
  basePadCurbEnabledVal: etichetta('base-pad-curb-enabled-val'),
  basePadCurbWidth: cursore('base-pad-curb-width'),
  basePadCurbWidthVal: etichetta('base-pad-curb-width-val'),
  basePadInnerRaise: cursore('base-pad-inner-raise'),
  basePadInnerRaiseVal: etichetta('base-pad-inner-raise-val'),
  basePadCurbSlope: cursore('base-pad-curb-slope'),
  basePadCurbSlopeVal: etichetta('base-pad-curb-slope-val'),
  basePadCurbRadius: cursore('base-pad-curb-radius'),
  basePadCurbRadiusVal: etichetta('base-pad-curb-radius-val'),
  basePadTextureMode: scelta('base-pad-texture-mode'),
  basePadTextureModeVal: etichetta('base-pad-texture-mode-val'),
  basePadTextureRepeat: cursore('base-pad-texture-repeat'),
  basePadTextureRepeatVal: etichetta('base-pad-texture-repeat-val'),
  basePadTextureRotation: cursore('base-pad-texture-rotation'),
  basePadTextureRotationVal: etichetta('base-pad-texture-rotation-val'),
  basePadNormal: cursore('base-pad-normal'),
  basePadNormalVal: etichetta('base-pad-normal-val'),
  basePadHue: cursore('base-pad-hue'),
  basePadHueVal: etichetta('base-pad-hue-val'),
  basePadSat: cursore('base-pad-sat'),
  basePadSatVal: etichetta('base-pad-sat-val'),
  basePadBright: cursore('base-pad-bright'),
  basePadBrightVal: etichetta('base-pad-bright-val'),
  basePadMetalness: cursore('base-pad-metalness'),
  basePadMetalnessVal: etichetta('base-pad-metalness-val'),
  basePadRoughness: cursore('base-pad-roughness'),
  basePadRoughnessVal: etichetta('base-pad-roughness-val'),
  basePadReflect: cursore('base-pad-reflect'),
  basePadReflectVal: etichetta('base-pad-reflect-val'),
  basePadEmissive: cursore('base-pad-emissive'),
  basePadEmissiveVal: etichetta('base-pad-emissive-val'),
  basePadBevelSize: cursore('base-pad-bevel-size'),
  basePadBevelSizeVal: etichetta('base-pad-bevel-size-val'),
  basePadBevelSegments: cursore('base-pad-bevel-segments'),
  basePadBevelSegmentsVal: etichetta('base-pad-bevel-segments-val'),
  basePadFlatShading: scelta('base-pad-flat-shading'),
  basePadFlatShadingVal: etichetta('base-pad-flat-shading-val'),
  basePadBorderOpacity: cursore('base-pad-border-opacity'),
  basePadBorderOpacityVal: etichetta('base-pad-border-opacity-val'),
  basePadBorderBright: cursore('base-pad-border-bright'),
  basePadBorderBrightVal: etichetta('base-pad-border-bright-val'),
  buildingLowLedOffset: cursore('building-low-led-offset'),
  buildingLowLedOffsetVal: etichetta('building-low-led-offset-val'),
  buildingHighLedOffset: cursore('building-high-led-offset'),
  buildingHighLedOffsetVal: etichetta('building-high-led-offset-val'),
  buildingVerticalLedLength: cursore('building-vertical-led-length'),
  buildingVerticalLedLengthVal: etichetta('building-vertical-led-length-val'),
  buildingVerticalLedY: cursore('building-vertical-led-y'),
  buildingVerticalLedYVal: etichetta('building-vertical-led-y-val'),
  buildingLowLedY: cursore('building-low-led-y'),
  buildingLowLedYVal: etichetta('building-low-led-y-val'),
  buildingHighLedY: cursore('building-high-led-y'),
  buildingHighLedYVal: etichetta('building-high-led-y-val'),
  buildingFacadeLedNormal: cursore('building-facade-led-normal'),
  buildingFacadeLedNormalVal: etichetta('building-facade-led-normal-val'),
  buildingFacadeLedX: cursore('building-facade-led-x'),
  buildingFacadeLedXVal: etichetta('building-facade-led-x-val'),
  buildingFacadeLedY: cursore('building-facade-led-y'),
  buildingFacadeLedYVal: etichetta('building-facade-led-y-val'),
  buildingFacadeLedZ: cursore('building-facade-led-z'),
  buildingFacadeLedZVal: etichetta('building-facade-led-z-val'),
  bridgeXOffset: cursore('bridge-x-offset'),
  bridgeXOffsetVal: etichetta('bridge-x-offset-val'),
  bridgeZOffset: cursore('bridge-z-offset'),
  bridgeZOffsetVal: etichetta('bridge-z-offset-val'),
  bridgeYOffset: cursore('bridge-y-offset'),
  bridgeYOffsetVal: etichetta('bridge-y-offset-val'),
  bridgeSpanScale: cursore('bridge-span-scale'),
  bridgeSpanScaleVal: etichetta('bridge-span-scale-val'),
  bridgeHeightScale: cursore('bridge-height-scale'),
  bridgeHeightScaleVal: etichetta('bridge-height-scale-val'),
  bridgeDepthScale: cursore('bridge-depth-scale'),
  bridgeDepthScaleVal: etichetta('bridge-depth-scale-val'),
  bridgeLowLedOffset: cursore('bridge-low-led-offset'),
  bridgeLowLedOffsetVal: etichetta('bridge-low-led-offset-val'),
  bridgeHighLedOffset: cursore('bridge-high-led-offset'),
  bridgeHighLedOffsetVal: etichetta('bridge-high-led-offset-val'),
  bridgeControls: etichetta('bridge-controls'),
  collisionPadding: cursore('collision-padding'),
  collisionPaddingVal: etichetta('collision-padding-val'),
  mainBuildingCollisionPadding: cursore('main-building-collision-padding'),
  mainBuildingCollisionPaddingVal: etichetta('main-building-collision-padding-val'),
  noclipEnabled: scelta('noclip-enabled'),
  noclipEnabledVal: etichetta('noclip-enabled-val'),
  cameraMinHeight: cursore('camera-min-height'),
  cameraMinHeightVal: etichetta('camera-min-height-val'),
  walkSpeed: cursore('walk-speed'),
  walkSpeedVal: etichetta('walk-speed-val'),
  sprintSpeed: cursore('sprint-speed'),
  sprintSpeedVal: etichetta('sprint-speed-val'),
  backwardSpeedScale: cursore('backward-speed-scale'),
  backwardSpeedScaleVal: etichetta('backward-speed-scale-val'),
  strafeSpeedScale: cursore('strafe-speed-scale'),
  strafeSpeedScaleVal: etichetta('strafe-speed-scale-val'),
  diagonalSpeedScale: cursore('diagonal-speed-scale'),
  diagonalSpeedScaleVal: etichetta('diagonal-speed-scale-val'),
  verticalSpeed: cursore('vertical-speed'),
  verticalSpeedVal: etichetta('vertical-speed-val'),
  movementAccel: cursore('movement-accel'),
  movementAccelVal: etichetta('movement-accel-val'),
  movementDecel: cursore('movement-decel'),
  movementDecelVal: etichetta('movement-decel-val'),
  walkBob: cursore('walk-bob'),
  walkBobVal: etichetta('walk-bob-val'),
  runBob: cursore('run-bob'),
  runBobVal: etichetta('run-bob-val'),
  strafeBobScale: cursore('strafe-bob-scale'),
  strafeBobScaleVal: etichetta('strafe-bob-scale-val'),
  backwardBobScale: cursore('backward-bob-scale'),
  backwardBobScaleVal: etichetta('backward-bob-scale-val'),
  walkStepRate: cursore('walk-step-rate'),
  walkStepRateVal: etichetta('walk-step-rate-val'),
  runStepRate: cursore('run-step-rate'),
  runStepRateVal: etichetta('run-step-rate-val'),
  stepSnap: cursore('step-snap'),
  stepSnapVal: etichetta('step-snap-val'),
  movementSway: cursore('movement-sway'),
  movementSwayVal: etichetta('movement-sway-val'),
  movementRoll: cursore('movement-roll'),
  movementRollVal: etichetta('movement-roll-val'),
  strafeLean: cursore('strafe-lean'),
  strafeLeanVal: etichetta('strafe-lean-val'),
  headMotionSmoothing: cursore('head-motion-smoothing'),
  headMotionSmoothingVal: etichetta('head-motion-smoothing-val'),
  mouseSensitivity: cursore('mouse-sensitivity'),
  mouseSensitivityVal: etichetta('mouse-sensitivity-val'),
  runnerBodyLight: cursore('runner-body-light'),
  runnerBodyLightVal: etichetta('runner-body-light-val'),
  runnerLineLight: cursore('runner-line-light'),
  runnerLineLightVal: etichetta('runner-line-light-val'),
  runnerKeyLight: cursore('runner-key-light'),
  runnerKeyLightVal: etichetta('runner-key-light-val'),
  runnerRimLight: cursore('runner-rim-light'),
  runnerRimLightVal: etichetta('runner-rim-light-val'),
  runnerFillLight: cursore('runner-fill-light'),
  runnerFillLightVal: etichetta('runner-fill-light-val'),
  runnerLedBrightness: cursore('runner-led-brightness'),
  runnerLedBrightnessVal: etichetta('runner-led-brightness-val'),
  runnerLedBloom: cursore('runner-led-bloom'),
  runnerLedBloomVal: etichetta('runner-led-bloom-val'),
  runnerBeatPulseEnabled: scelta('runner-beat-pulse-enabled'),
  runnerBeatPulseEnabledVal: etichetta('runner-beat-pulse-enabled-val'),
  runnerBeatPulseBpm: cursore('runner-beat-pulse-bpm'),
  runnerBeatPulseBpmVal: etichetta('runner-beat-pulse-bpm-val'),
  runnerBeatPulseOffset: cursore('runner-beat-pulse-offset'),
  runnerBeatPulseOffsetVal: etichetta('runner-beat-pulse-offset-val'),
  runnerBeatPulseIntensity: cursore('runner-beat-pulse-intensity'),
  runnerBeatPulseIntensityVal: etichetta('runner-beat-pulse-intensity-val'),
  runnerBeatPulseDecay: cursore('runner-beat-pulse-decay'),
  runnerBeatPulseDecayVal: etichetta('runner-beat-pulse-decay-val'),
  runnerBeatPulseDivision: cursore('runner-beat-pulse-division'),
  runnerBeatPulseDivisionVal: etichetta('runner-beat-pulse-division-val'),
  runnerMaterialReflect: cursore('runner-material-reflect'),
  runnerMaterialReflectVal: etichetta('runner-material-reflect-val'),
  runnerMaterialMetalness: cursore('runner-material-metalness'),
  runnerMaterialMetalnessVal: etichetta('runner-material-metalness-val'),
  runnerMaterialRoughness: cursore('runner-material-roughness'),
  runnerMaterialRoughnessVal: etichetta('runner-material-roughness-val'),
  characterBubbleBgOpacity: cursore('character-bubble-bg-opacity'),
  characterBubbleBgOpacityVal: etichetta('character-bubble-bg-opacity-val'),
  runnerFloorReflection: cursore('runner-floor-reflection'),
  runnerFloorReflectionVal: etichetta('runner-floor-reflection-val'),
  runnerFloorReflectionScale: cursore('runner-floor-reflection-scale'),
  runnerFloorReflectionScaleVal: etichetta('runner-floor-reflection-scale-val'),
  runnerShadowSoftness: cursore('runner-shadow-softness'),
  runnerShadowSoftnessVal: etichetta('runner-shadow-softness-val'),
  runnerShadowPulse: cursore('runner-shadow-pulse'),
  runnerShadowPulseVal: etichetta('runner-shadow-pulse-val'),
  runnerShadowCyan: cursore('runner-shadow-cyan'),
  runnerShadowCyanVal: etichetta('runner-shadow-cyan-val'),
  runnerShadowOffsetX: cursore('runner-shadow-offset-x'),
  runnerShadowOffsetXVal: etichetta('runner-shadow-offset-x-val'),
  runnerShadowOffsetZ: cursore('runner-shadow-offset-z'),
  runnerShadowOffsetZVal: etichetta('runner-shadow-offset-z-val'),
  runnerKeyLightY: cursore('runner-key-light-y'),
  runnerKeyLightYVal: etichetta('runner-key-light-y-val'),
  runnerKeyLightZ: cursore('runner-key-light-z'),
  runnerKeyLightZVal: etichetta('runner-key-light-z-val'),
  runnerRimLightX: cursore('runner-rim-light-x'),
  runnerRimLightXVal: etichetta('runner-rim-light-x-val'),
  runnerFillLightY: cursore('runner-fill-light-y'),
  runnerFillLightYVal: etichetta('runner-fill-light-y-val'),
  runnerScale: cursore('runner-scale'),
  runnerScaleVal: etichetta('runner-scale-val'),
  runnerAnimationSpeed: cursore('runner-animation-speed'),
  runnerAnimationSpeedVal: etichetta('runner-animation-speed-val'),
  runnerWalkSpeed: cursore('runner-walk-speed'),
  runnerWalkSpeedVal: etichetta('runner-walk-speed-val'),
  runnerStrideSync: cursore('runner-stride-sync'),
  runnerStrideSyncVal: etichetta('runner-stride-sync-val'),
  sideBuildingBrightness: cursore('side-building-brightness'),
  sideBuildingBrightnessVal: etichetta('side-building-brightness-val'),
  sideBuildingHue: cursore('side-building-hue'),
  sideBuildingHueVal: etichetta('side-building-hue-val'),
  sideBuildingMetalness: cursore('side-building-metalness'),
  sideBuildingMetalnessVal: etichetta('side-building-metalness-val'),
  sideBuildingRoughness: cursore('side-building-roughness'),
  sideBuildingRoughnessVal: etichetta('side-building-roughness-val'),
  sideBuildingReflect: cursore('side-building-reflect'),
  sideBuildingReflectVal: etichetta('side-building-reflect-val'),
  sideBuildingEmissive: cursore('side-building-emissive'),
  sideBuildingEmissiveVal: etichetta('side-building-emissive-val'),
  sideBuildingWidthScale: cursore('side-building-width-scale'),
  sideBuildingWidthScaleVal: etichetta('side-building-width-scale-val'),
  sideBuildingDepthScale: cursore('side-building-depth-scale'),
  sideBuildingDepthScaleVal: etichetta('side-building-depth-scale-val'),
  sideBuildingSpacingScale: cursore('side-building-spacing-scale'),
  sideBuildingSpacingScaleVal: etichetta('side-building-spacing-scale-val'),
  sideBuildingScale: cursore('side-building-height-scale'),
  sideBuildingScaleVal: etichetta('side-building-height-scale-val'),
  sideBuildingBasePadScale: cursore('side-building-base-pad-scale'),
  sideBuildingBasePadScaleVal: etichetta('side-building-base-pad-scale-val'),
  sideBuildingBasePadXScale: cursore('side-building-base-pad-x-scale'),
  sideBuildingBasePadXScaleVal: etichetta('side-building-base-pad-x-scale-val'),
  sideBuildingBasePadY: cursore('side-building-base-pad-y'),
  sideBuildingBasePadYVal: etichetta('side-building-base-pad-y-val'),
  sideBuildingBasePadThickness: cursore('side-building-base-pad-thickness'),
  sideBuildingBasePadThicknessVal: etichetta('side-building-base-pad-thickness-val'),
  sideBuildingBasePadCut: cursore('side-building-base-pad-cut'),
  sideBuildingBasePadCutVal: etichetta('side-building-base-pad-cut-val'),
  sideBuildingBasePadRadius: cursore('side-building-base-pad-radius'),
  sideBuildingBasePadRadiusVal: etichetta('side-building-base-pad-radius-val'),
  mainBuildingBrightness: cursore('main-building-brightness'),
  mainBuildingBrightnessVal: etichetta('main-building-brightness-val'),
  mainBuildingHue: cursore('main-building-hue'),
  mainBuildingHueVal: etichetta('main-building-hue-val'),
  mainBuildingSaturation: cursore('main-building-saturation'),
  mainBuildingSaturationVal: etichetta('main-building-saturation-val'),
  mainBuildingMetalness: cursore('main-building-metalness'),
  mainBuildingMetalnessVal: etichetta('main-building-metalness-val'),
  mainBuildingRoughness: cursore('main-building-roughness'),
  mainBuildingRoughnessVal: etichetta('main-building-roughness-val'),
  mainBuildingReflect: cursore('main-building-reflect'),
  mainBuildingReflectVal: etichetta('main-building-reflect-val'),
  mainBuildingEmissive: cursore('main-building-emissive'),
  mainBuildingEmissiveVal: etichetta('main-building-emissive-val'),
  mainBuildingWidthScale: cursore('main-building-width-scale'),
  mainBuildingWidthScaleVal: etichetta('main-building-width-scale-val'),
  mainBuildingDepthScale: cursore('main-building-depth-scale'),
  mainBuildingDepthScaleVal: etichetta('main-building-depth-scale-val'),
  mainBuildingZ: cursore('main-building-z'),
  mainBuildingZVal: etichetta('main-building-z-val'),
  mainBuildingY: cursore('main-building-y'),
  mainBuildingYVal: etichetta('main-building-y-val'),
  mainBuildingScale: cursore('main-building-height-scale'),
  mainBuildingScaleVal: etichetta('main-building-height-scale-val'),
  mainBuildingBasePadScale: cursore('main-building-base-pad-scale'),
  mainBuildingBasePadScaleVal: etichetta('main-building-base-pad-scale-val'),
  mainBuildingBasePadXScale: cursore('main-building-base-pad-x-scale'),
  mainBuildingBasePadXScaleVal: etichetta('main-building-base-pad-x-scale-val'),
  mainBuildingBasePadZScale: cursore('main-building-base-pad-z-scale'),
  mainBuildingBasePadZScaleVal: etichetta('main-building-base-pad-z-scale-val'),
  mainBuildingBasePadY: cursore('main-building-base-pad-y'),
  mainBuildingBasePadYVal: etichetta('main-building-base-pad-y-val'),
  mainBuildingBasePadThickness: cursore('main-building-base-pad-thickness'),
  mainBuildingBasePadThicknessVal: etichetta('main-building-base-pad-thickness-val'),
  mainBuildingBasePadCut: cursore('main-building-base-pad-cut'),
  mainBuildingBasePadCutVal: etichetta('main-building-base-pad-cut-val'),
  mainBuildingBasePadRadius: cursore('main-building-base-pad-radius'),
  mainBuildingBasePadRadiusVal: etichetta('main-building-base-pad-radius-val'),
  mainBuildingLedBrightness: cursore('main-building-led-brightness'),
  mainBuildingLedBrightnessVal: etichetta('main-building-led-brightness-val'),
  mainBuildingLedThickness: cursore('main-building-led-thickness'),
  mainBuildingLedThicknessVal: etichetta('main-building-led-thickness-val'),
  mainBuildingLedDistance: cursore('main-building-led-distance'),
  mainBuildingLedDistanceVal: etichetta('main-building-led-distance-val'),
  mainBuildingHorizontalLedDistance: cursore('main-building-horizontal-led-distance'),
  mainBuildingHorizontalLedDistanceVal: etichetta('main-building-horizontal-led-distance-val'),
  mainBuildingHorizontalLedThickness: cursore('main-building-horizontal-led-thickness'),
  mainBuildingHorizontalLedThicknessVal: etichetta('main-building-horizontal-led-thickness-val'),
  mainBuildingHorizontalLedRadius: cursore('main-building-horizontal-led-radius'),
  mainBuildingHorizontalLedRadiusVal: etichetta('main-building-horizontal-led-radius-val'),
  mainBuildingLedHue: cursore('main-building-led-hue'),
  mainBuildingLedHueVal: etichetta('main-building-led-hue-val'),
  mainBuildingLowLedOffset: cursore('main-building-low-led-offset'),
  mainBuildingLowLedOffsetVal: etichetta('main-building-low-led-offset-val'),
  mainBuildingHighLedOffset: cursore('main-building-high-led-offset'),
  mainBuildingHighLedOffsetVal: etichetta('main-building-high-led-offset-val'),
  mainBuildingVerticalLedLength: cursore('main-building-vertical-led-length'),
  mainBuildingVerticalLedLengthVal: etichetta('main-building-vertical-led-length-val'),
  mainBuildingVerticalLedY: cursore('main-building-vertical-led-y'),
  mainBuildingVerticalLedYVal: etichetta('main-building-vertical-led-y-val'),
  mainBuildingLowLedY: cursore('main-building-low-led-y'),
  mainBuildingLowLedYVal: etichetta('main-building-low-led-y-val'),
  mainBuildingHighLedY: cursore('main-building-high-led-y'),
  mainBuildingHighLedYVal: etichetta('main-building-high-led-y-val'),
  mainLedBrightnessUi: cursore('main-led-brightness-ui'),
  mainLedBrightnessUiVal: etichetta('main-led-brightness-ui-val'),
  mainLedHueUi: cursore('main-led-hue-ui'),
  mainLedHueUiVal: etichetta('main-led-hue-ui-val'),
  mainLedVerticalDistanceUi: cursore('main-led-vertical-distance-ui'),
  mainLedVerticalDistanceUiVal: etichetta('main-led-vertical-distance-ui-val'),
  mainLedThicknessUi: cursore('main-led-thickness-ui'),
  mainLedThicknessUiVal: etichetta('main-led-thickness-ui-val'),
  mainLedVerticalLengthUi: cursore('main-led-vertical-length-ui'),
  mainLedVerticalLengthUiVal: etichetta('main-led-vertical-length-ui-val'),
  mainLedVerticalYUi: cursore('main-led-vertical-y-ui'),
  mainLedVerticalYUiVal: etichetta('main-led-vertical-y-ui-val'),
  mainLedHorizontalDistanceUi: cursore('main-led-horizontal-distance-ui'),
  mainLedHorizontalDistanceUiVal: etichetta('main-led-horizontal-distance-ui-val'),
  mainLedHorizontalThicknessUi: cursore('main-led-horizontal-thickness-ui'),
  mainLedHorizontalThicknessUiVal: etichetta('main-led-horizontal-thickness-ui-val'),
  mainLedHorizontalRadiusUi: cursore('main-led-horizontal-radius-ui'),
  mainLedHorizontalRadiusUiVal: etichetta('main-led-horizontal-radius-ui-val'),
  mainLedLowOffsetUi: cursore('main-led-low-offset-ui'),
  mainLedLowOffsetUiVal: etichetta('main-led-low-offset-ui-val'),
  mainLedLowYUi: cursore('main-led-low-y-ui'),
  mainLedLowYUiVal: etichetta('main-led-low-y-ui-val'),
  mainLedHighOffsetUi: cursore('main-led-high-offset-ui'),
  mainLedHighOffsetUiVal: etichetta('main-led-high-offset-ui-val'),
  mainLedHighYUi: cursore('main-led-high-y-ui'),
  mainLedHighYUiVal: etichetta('main-led-high-y-ui-val'),
  mainFacadeLedBrightnessUi: cursore('main-facade-led-brightness-ui'),
  mainFacadeLedBrightnessUiVal: etichetta('main-facade-led-brightness-ui-val'),
  mainFacadeLedNormalUi: cursore('main-facade-led-normal-ui'),
  mainFacadeLedNormalUiVal: etichetta('main-facade-led-normal-ui-val'),
  mainFacadeLedXUi: cursore('main-facade-led-x-ui'),
  mainFacadeLedXUiVal: etichetta('main-facade-led-x-ui-val'),
  mainFacadeLedYUi: cursore('main-facade-led-y-ui'),
  mainFacadeLedYUiVal: etichetta('main-facade-led-y-ui-val'),
  mainFacadeLedZUi: cursore('main-facade-led-z-ui'),
  mainFacadeLedZUiVal: etichetta('main-facade-led-z-ui-val'),
  mainFacadeLedThicknessUi: cursore('main-facade-led-thickness-ui'),
  mainFacadeLedThicknessUiVal: etichetta('main-facade-led-thickness-ui-val'),
  mainFacadeLedSegmentControls: Array.from({ length: 6 }, (_, index) => ({
    u: cursore(`main-facade-led-seg-${index + 1}-u-ui`),
    uVal: etichetta(`main-facade-led-seg-${index + 1}-u-ui-val`),
    y: cursore(`main-facade-led-seg-${index + 1}-y-ui`),
    yVal: etichetta(`main-facade-led-seg-${index + 1}-y-ui-val`),
    normal: cursore(`main-facade-led-seg-${index + 1}-normal-ui`),
    normalVal: etichetta(`main-facade-led-seg-${index + 1}-normal-ui-val`),
  })),
  performanceMode: scelta('performance-mode'),
  renderResolution: cursore('render-resolution'),
  renderResolutionVal: etichetta('render-resolution-val'),
  aaMode: scelta('aa-mode'),
  bloomEnabled: scelta('bloom-enabled'),
  bloomStrength: cursore('bloom-strength'),
  bloomVal: etichetta('bloom-val'),
  bloomRadius: cursore('bloom-radius'),
  bloomRadiusVal: etichetta('bloom-radius-val'),
  bloomThreshold: cursore('bloom-threshold'),
  bloomThresholdVal: etichetta('bloom-threshold-val'),
  bloomQuality: cursore('bloom-quality'),
  bloomQualityVal: etichetta('bloom-quality-val'),
  pixelRatio: cursore('pixel-ratio'),
  pixelRatioVal: etichetta('pixel-ratio-val'),
  fsrPreset: scelta('fsr-preset'),
  fsrUpscaleEnabled: scelta('fsr-upscale-enabled'),
  fsrInternalScale: cursore('fsr-internal-scale'),
  fsrInternalScaleVal: etichetta('fsr-internal-scale-val'),
  fsrSharpness: cursore('fsr-sharpness'),
  fsrSharpnessVal: etichetta('fsr-sharpness-val'),
  runFsrBenchmark: bottone('run-fsr-benchmark'),
  fsrBenchmarkResults: etichetta('fsr-benchmark-results'),
  wireframeEnabled: scelta('wireframe-enabled'),
  wireframeEnabledVal: etichetta('wireframe-enabled-val'),
  wireframeDelay: cursore('wireframe-delay'),
  wireframeDelayVal: etichetta('wireframe-delay-val'),
  wireframeFade: cursore('wireframe-fade'),
  wireframeFadeVal: etichetta('wireframe-fade-val'),
  wireframeDensity: cursore('wireframe-density'),
  wireframeDensityVal: etichetta('wireframe-density-val'),
  wireframeOpacity: cursore('wireframe-opacity'),
  wireframeOpacityVal: etichetta('wireframe-opacity-val'),
  wireframeBackplate: cursore('wireframe-backplate'),
  wireframeBackplateVal: etichetta('wireframe-backplate-val'),
  musicFxEnabled: scelta('music-fx-enabled'),
  musicFxEnabledVal: etichetta('music-fx-enabled-val'),
  musicFxMix: cursore('music-fx-mix'),
  musicFxMixVal: etichetta('music-fx-mix-val'),
  musicFxCrusher: cursore('music-fx-crusher'),
  musicFxCrusherVal: etichetta('music-fx-crusher-val'),
  musicFxBitDepth: cursore('music-fx-bit-depth'),
  musicFxBitDepthVal: etichetta('music-fx-bit-depth-val'),
  musicFxHighpass: cursore('music-fx-highpass'),
  musicFxHighpassVal: etichetta('music-fx-highpass-val'),
  musicFxLowpass: cursore('music-fx-lowpass'),
  musicFxLowpassVal: etichetta('music-fx-lowpass-val'),
  musicFxDistortion: cursore('music-fx-distortion'),
  musicFxDistortionVal: etichetta('music-fx-distortion-val'),
  musicFxTelephone: cursore('music-fx-telephone'),
  musicFxTelephoneVal: etichetta('music-fx-telephone-val'),
  musicFxWobble: cursore('music-fx-wobble'),
  musicFxWobbleVal: etichetta('music-fx-wobble-val'),
  musicFxNoise: cursore('music-fx-noise'),
  musicFxNoiseVal: etichetta('music-fx-noise-val'),
  resetCameraHeight: bottone('reset-camera-height'),
  playerSpawnVal: etichetta('player-spawn-val'),
  saveLiveSpawn: bottone('save-live-spawn'),
  resetPlayerSpawn: bottone('reset-player-spawn'),
  startPositionLiveVal: etichetta('start-position-live-val'),
  startPositionSavedVal: etichetta('start-position-saved-val'),
  saveStartPosition: bottone('save-start-position'),
  goStartPosition: bottone('go-start-position'),
  droneIntroFlight: bottone('drone-intro-flight'),
  };
}

export const PRODUCTION_CONTROL_PANELS = new Set([
  'movement',
  'character',
  'surface-reflections',
  'bloom-fx',
  'led-glow-fx',
  'central-building-leds',
  'wireframe-fx',
  'audio-fx',
  'atmosphere-fx',
  'performance-fx',
]);
export const PRODUCTION_LIVE_CONTROL_SELECTOR = Array.from(PRODUCTION_CONTROL_PANELS).flatMap((panel) => [
  `#hud-controls .control-panel[data-panel="${panel}"] input[type="range"]`,
  `#hud-controls .control-panel[data-panel="${panel}"] input[type="checkbox"]`,
  `#hud-controls .control-panel[data-panel="${panel}"] select`,
]).join(',');

export const SKY_FAST_CONTROL_IDS = new Set([
  'sky-choice',
  'sky-quality',
  'sky-brightness',
  'sky-hue',
  'sky-cloud-contrast',
  'sky-storm-frequency',
  'sky-storm-intensity',
  'sky-storm-size',
  'sky-storm-cloud-threshold',
  'sky-storm-band',
  'sky-storm-veil',
]);
export const POST_FAST_CONTROL_IDS = new Set([
  'performance-mode',
  'render-resolution',
  'aa-mode',
  'bloom-enabled',
  'bloom-strength',
  'bloom-radius',
  'bloom-threshold',
  'bloom-quality',
  'pixel-ratio',
  'fsr-preset',
  'fsr-upscale-enabled',
  'fsr-internal-scale',
  'fsr-sharpness',
]);
export const WIREFRAME_FAST_CONTROL_IDS = new Set([
  'wireframe-enabled',
  'wireframe-delay',
  'wireframe-fade',
  'wireframe-density',
  'wireframe-opacity',
  'wireframe-backplate',
]);
export const AUDIO_FX_FAST_CONTROL_IDS = new Set([
  'music-fx-enabled',
  'music-fx-mix',
  'music-fx-crusher',
  'music-fx-bit-depth',
  'music-fx-highpass',
  'music-fx-lowpass',
  'music-fx-distortion',
  'music-fx-telephone',
  'music-fx-wobble',
  'music-fx-noise',
]);
export const MOVEMENT_FAST_CONTROL_IDS = new Set([
  'collision-padding',
  'main-building-collision-padding',
  'noclip-enabled',
  'camera-min-height',
  'walk-speed',
  'sprint-speed',
  'backward-speed-scale',
  'strafe-speed-scale',
  'diagonal-speed-scale',
  'vertical-speed',
  'movement-accel',
  'movement-decel',
  'walk-bob',
  'run-bob',
  'strafe-bob-scale',
  'backward-bob-scale',
  'walk-step-rate',
  'run-step-rate',
  'step-snap',
  'movement-sway',
  'movement-roll',
  'strafe-lean',
  'head-motion-smoothing',
  'mouse-sensitivity',
]);
export const CHARACTER_FAST_CONTROL_IDS = new Set([
  'runner-body-light',
  'runner-line-light',
  'runner-key-light',
  'runner-rim-light',
  'runner-fill-light',
  'runner-led-brightness',
  'runner-led-bloom',
  'runner-beat-pulse-enabled',
  'runner-beat-pulse-bpm',
  'runner-beat-pulse-offset',
  'runner-beat-pulse-intensity',
  'runner-beat-pulse-decay',
  'runner-beat-pulse-division',
  'runner-material-reflect',
  'runner-material-metalness',
  'runner-material-roughness',
  'character-bubble-bg-opacity',
  'runner-floor-reflection',
  'runner-floor-reflection-scale',
  'runner-shadow-softness',
  'runner-shadow-pulse',
  'runner-shadow-cyan',
  'runner-shadow-offset-x',
  'runner-shadow-offset-z',
  'runner-key-light-y',
  'runner-key-light-z',
  'runner-rim-light-x',
  'runner-fill-light-y',
  'runner-scale',
  'runner-animation-speed',
  'runner-walk-speed',
  'runner-stride-sync',
]);
export const LIGHT_FAST_CONTROL_IDS = new Set(['ambient-light', 'key-light', 'exposure']);
export const HEX_RUNTIME_FAST_CONTROL_IDS = new Set([
  'hex-offset',
  'hex-radius',
  'hex-drop-delay',
  'hex-drop-speed',
  'hex-recovery',
  'tile-hit-light',
  'player-tile-light',
]);
export const ROAD_MATERIAL_FAST_CONTROL_IDS = new Set([
  'road-normal',
  'road-light',
  'road-reflect',
  'road-building-reflect',
  'road-metalness',
  'road-roughness',
  'road-hue',
  'road-sat',
  'road-bright',
]);
export const BUILDING_MATERIAL_FAST_CONTROL_IDS = new Set([
  'side-building-brightness',
  'side-building-hue',
  'side-building-metalness',
  'side-building-roughness',
  'side-building-reflect',
  'side-building-emissive',
  'main-building-brightness',
  'main-building-hue',
  'main-building-metalness',
  'main-building-roughness',
  'main-building-reflect',
  'main-building-emissive',
]);
export const BASE_PAD_MATERIAL_FAST_CONTROL_IDS = new Set([
  'base-pad-texture-mode',
  'base-pad-texture-repeat',
  'base-pad-texture-rotation',
  'base-pad-normal',
  'base-pad-hue',
  'base-pad-sat',
  'base-pad-bright',
  'base-pad-metalness',
  'base-pad-roughness',
  'base-pad-reflect',
  'base-pad-emissive',
  'base-pad-flat-shading',
  'base-pad-border-opacity',
  'base-pad-border-bright',
]);
export const BOUNDARY_ERROR_FAST_CONTROL_IDS = new Set([
  'road-boundary-collision-enabled',
  'road-boundary-collision-margin',
  'road-boundary-camera-lead',
  'road-boundary-pulse-strength',
  'boundary-error-visible',
  'boundary-error-size',
  'boundary-error-anchor',
  'boundary-error-animation',
  'boundary-error-duration',
  'boundary-error-glitch',
  'boundary-error-render-mode',
  'boundary-error-floor-light-enabled',
  'boundary-error-floor-light-radius',
  'boundary-error-floor-light-intensity',
  'boundary-error-floor-light-opacity',
  'boundary-error-floor-light-hue',
  'boundary-error-floor-light-y',
  'boundary-error-floor-light-softness',
]);
