export function createControlEls() {
  return {
  hexOffset: document.getElementById('hex-offset'),
  hexOffsetVal: document.getElementById('hex-offset-val'),
  hexRadius: document.getElementById('hex-radius'),
  hexRadiusVal: document.getElementById('hex-radius-val'),
  hexDropDelay: document.getElementById('hex-drop-delay'),
  hexDropDelayVal: document.getElementById('hex-drop-delay-val'),
  hexDropSpeed: document.getElementById('hex-drop-speed'),
  hexDropSpeedVal: document.getElementById('hex-drop-speed-val'),
  hexRecovery: document.getElementById('hex-recovery'),
  hexRecoveryVal: document.getElementById('hex-recovery-val'),
  tileHeight: document.getElementById('tile-height'),
  tileHeightVal: document.getElementById('tile-height-val'),
  tileScale: document.getElementById('tile-scale'),
  tileScaleVal: document.getElementById('tile-scale-val'),
  hexGap: document.getElementById('hex-gap'),
  hexGapVal: document.getElementById('hex-gap-val'),
  tileHitLight: document.getElementById('tile-hit-light'),
  tileHitLightVal: document.getElementById('tile-hit-light-val'),
  playerTileLight: document.getElementById('player-tile-light'),
  playerTileLightVal: document.getElementById('player-tile-light-val'),
  roadNormal: document.getElementById('road-normal'),
  roadNormalVal: document.getElementById('road-normal-val'),
  ambientLight: document.getElementById('ambient-light'),
  ambientVal: document.getElementById('ambient-val'),
  keyLight: document.getElementById('key-light'),
  keyVal: document.getElementById('key-val'),
  exposure: document.getElementById('exposure'),
  exposureVal: document.getElementById('exposure-val'),
  skyChoice: document.getElementById('sky-choice'),
  skyQuality: document.getElementById('sky-quality'),
  skyBrightness: document.getElementById('sky-brightness'),
  skyBrightnessVal: document.getElementById('sky-brightness-val'),
  skyHue: document.getElementById('sky-hue'),
  skyHueVal: document.getElementById('sky-hue-val'),
  skyCloudContrast: document.getElementById('sky-cloud-contrast'),
  skyCloudContrastVal: document.getElementById('sky-cloud-contrast-val'),
  skyStormFrequency: document.getElementById('sky-storm-frequency'),
  skyStormFrequencyVal: document.getElementById('sky-storm-frequency-val'),
  skyStormIntensity: document.getElementById('sky-storm-intensity'),
  skyStormIntensityVal: document.getElementById('sky-storm-intensity-val'),
  skyStormSize: document.getElementById('sky-storm-size'),
  skyStormSizeVal: document.getElementById('sky-storm-size-val'),
  skyStormCloudThreshold: document.getElementById('sky-storm-cloud-threshold'),
  skyStormCloudThresholdVal: document.getElementById('sky-storm-cloud-threshold-val'),
  skyStormBand: document.getElementById('sky-storm-band'),
  skyStormBandVal: document.getElementById('sky-storm-band-val'),
  skyStormVeil: document.getElementById('sky-storm-veil'),
  skyStormVeilVal: document.getElementById('sky-storm-veil-val'),
  boulevardWidthScale: document.getElementById('boulevard-width-scale'),
  boulevardWidthScaleVal: document.getElementById('boulevard-width-scale-val'),
  roadLight: document.getElementById('road-light'),
  roadLightVal: document.getElementById('road-light-val'),
  roadReflect: document.getElementById('road-reflect'),
  roadReflectVal: document.getElementById('road-reflect-val'),
  roadBuildingReflect: document.getElementById('road-building-reflect'),
  roadBuildingReflectVal: document.getElementById('road-building-reflect-val'),
  roadMetalness: document.getElementById('road-metalness'),
  roadMetalnessVal: document.getElementById('road-metalness-val'),
  roadRoughness: document.getElementById('road-roughness'),
  roadRoughnessVal: document.getElementById('road-roughness-val'),
  roadHue: document.getElementById('road-hue'),
  roadHueVal: document.getElementById('road-hue-val'),
  roadSat: document.getElementById('road-sat'),
  roadSatVal: document.getElementById('road-sat-val'),
  roadBright: document.getElementById('road-bright'),
  roadBrightVal: document.getElementById('road-bright-val'),
  roadBoundaryHexEnabled: document.getElementById('road-boundary-hex-enabled'),
  roadBoundaryHexEnabledVal: document.getElementById('road-boundary-hex-enabled-val'),
  roadBoundaryHexRows: document.getElementById('road-boundary-hex-rows'),
  roadBoundaryHexRowsVal: document.getElementById('road-boundary-hex-rows-val'),
  roadSideHexExtraRows: document.getElementById('road-side-hex-extra-rows'),
  roadSideHexExtraRowsVal: document.getElementById('road-side-hex-extra-rows-val'),
  roadBoundaryHexBrightness: document.getElementById('road-boundary-hex-brightness'),
  roadBoundaryHexBrightnessVal: document.getElementById('road-boundary-hex-brightness-val'),
  roadBoundaryHexOpacity: document.getElementById('road-boundary-hex-opacity'),
  roadBoundaryHexOpacityVal: document.getElementById('road-boundary-hex-opacity-val'),
  roadBoundaryHexY: document.getElementById('road-boundary-hex-y'),
  roadBoundaryHexYVal: document.getElementById('road-boundary-hex-y-val'),
  roadBoundaryHexOutset: document.getElementById('road-boundary-hex-outset'),
  roadBoundaryHexOutsetVal: document.getElementById('road-boundary-hex-outset-val'),
  roadBoundaryRowY: Array.from({ length: 10 }, (_, index) => document.getElementById(`road-boundary-row-${index + 1}-y`)),
  roadBoundaryRowYVal: Array.from({ length: 10 }, (_, index) => document.getElementById(`road-boundary-row-${index + 1}-y-val`)),
  roadBoundaryCollisionEnabled: document.getElementById('road-boundary-collision-enabled'),
  roadBoundaryCollisionEnabledVal: document.getElementById('road-boundary-collision-enabled-val'),
  roadBoundaryCollisionMargin: document.getElementById('road-boundary-collision-margin'),
  roadBoundaryCollisionMarginVal: document.getElementById('road-boundary-collision-margin-val'),
  roadBoundaryCameraLead: document.getElementById('road-boundary-camera-lead'),
  roadBoundaryCameraLeadVal: document.getElementById('road-boundary-camera-lead-val'),
  roadBoundaryPulseStrength: document.getElementById('road-boundary-pulse-strength'),
  roadBoundaryPulseStrengthVal: document.getElementById('road-boundary-pulse-strength-val'),
  boundaryErrorVisible: document.getElementById('boundary-error-visible'),
  boundaryErrorVisibleVal: document.getElementById('boundary-error-visible-val'),
  boundaryErrorSize: document.getElementById('boundary-error-size'),
  boundaryErrorSizeVal: document.getElementById('boundary-error-size-val'),
  boundaryErrorAnchor: document.getElementById('boundary-error-anchor'),
  boundaryErrorAnchorVal: document.getElementById('boundary-error-anchor-val'),
  boundaryErrorAnimation: document.getElementById('boundary-error-animation'),
  boundaryErrorAnimationVal: document.getElementById('boundary-error-animation-val'),
  boundaryErrorDuration: document.getElementById('boundary-error-duration'),
  boundaryErrorDurationVal: document.getElementById('boundary-error-duration-val'),
  boundaryErrorGlitch: document.getElementById('boundary-error-glitch'),
  boundaryErrorGlitchVal: document.getElementById('boundary-error-glitch-val'),
  boundaryErrorRenderMode: document.getElementById('boundary-error-render-mode'),
  boundaryErrorRenderModeVal: document.getElementById('boundary-error-render-mode-val'),
  boundaryErrorFloorLightEnabled: document.getElementById('boundary-error-floor-light-enabled'),
  boundaryErrorFloorLightEnabledVal: document.getElementById('boundary-error-floor-light-enabled-val'),
  boundaryErrorFloorLightRadius: document.getElementById('boundary-error-floor-light-radius'),
  boundaryErrorFloorLightRadiusVal: document.getElementById('boundary-error-floor-light-radius-val'),
  boundaryErrorFloorLightIntensity: document.getElementById('boundary-error-floor-light-intensity'),
  boundaryErrorFloorLightIntensityVal: document.getElementById('boundary-error-floor-light-intensity-val'),
  boundaryErrorFloorLightOpacity: document.getElementById('boundary-error-floor-light-opacity'),
  boundaryErrorFloorLightOpacityVal: document.getElementById('boundary-error-floor-light-opacity-val'),
  boundaryErrorFloorLightHue: document.getElementById('boundary-error-floor-light-hue'),
  boundaryErrorFloorLightHueVal: document.getElementById('boundary-error-floor-light-hue-val'),
  boundaryErrorFloorLightY: document.getElementById('boundary-error-floor-light-y'),
  boundaryErrorFloorLightYVal: document.getElementById('boundary-error-floor-light-y-val'),
  boundaryErrorFloorLightSoftness: document.getElementById('boundary-error-floor-light-softness'),
  boundaryErrorFloorLightSoftnessVal: document.getElementById('boundary-error-floor-light-softness-val'),
  ledBrightness: document.getElementById('led-brightness'),
  ledBrightnessVal: document.getElementById('led-brightness-val'),
  ledThickness: document.getElementById('led-thickness'),
  ledThicknessVal: document.getElementById('led-thickness-val'),
  ledDistance: document.getElementById('led-distance'),
  ledDistanceVal: document.getElementById('led-distance-val'),
  buildingHorizontalLedDistance: document.getElementById('building-horizontal-led-distance'),
  buildingHorizontalLedDistanceVal: document.getElementById('building-horizontal-led-distance-val'),
  buildingHorizontalLedThickness: document.getElementById('building-horizontal-led-thickness'),
  buildingHorizontalLedThicknessVal: document.getElementById('building-horizontal-led-thickness-val'),
  buildingHorizontalLedRadius: document.getElementById('building-horizontal-led-radius'),
  buildingHorizontalLedRadiusVal: document.getElementById('building-horizontal-led-radius-val'),
  ledHue: document.getElementById('led-hue'),
  ledHueVal: document.getElementById('led-hue-val'),
  basePadLedBrightness: document.getElementById('base-pad-led-brightness'),
  basePadLedBrightnessVal: document.getElementById('base-pad-led-brightness-val'),
  basePadLedThickness: document.getElementById('base-pad-led-thickness'),
  basePadLedThicknessVal: document.getElementById('base-pad-led-thickness-val'),
  basePadLedOffset: document.getElementById('base-pad-led-offset'),
  basePadLedOffsetVal: document.getElementById('base-pad-led-offset-val'),
  basePadLedHue: document.getElementById('base-pad-led-hue'),
  basePadLedHueVal: document.getElementById('base-pad-led-hue-val'),
  basePadGlobalY: document.getElementById('base-pad-global-y'),
  basePadGlobalYVal: document.getElementById('base-pad-global-y-val'),
  basePadCurbEnabled: document.getElementById('base-pad-curb-enabled'),
  basePadCurbEnabledVal: document.getElementById('base-pad-curb-enabled-val'),
  basePadCurbWidth: document.getElementById('base-pad-curb-width'),
  basePadCurbWidthVal: document.getElementById('base-pad-curb-width-val'),
  basePadInnerRaise: document.getElementById('base-pad-inner-raise'),
  basePadInnerRaiseVal: document.getElementById('base-pad-inner-raise-val'),
  basePadCurbSlope: document.getElementById('base-pad-curb-slope'),
  basePadCurbSlopeVal: document.getElementById('base-pad-curb-slope-val'),
  basePadCurbRadius: document.getElementById('base-pad-curb-radius'),
  basePadCurbRadiusVal: document.getElementById('base-pad-curb-radius-val'),
  basePadTextureMode: document.getElementById('base-pad-texture-mode'),
  basePadTextureModeVal: document.getElementById('base-pad-texture-mode-val'),
  basePadTextureRepeat: document.getElementById('base-pad-texture-repeat'),
  basePadTextureRepeatVal: document.getElementById('base-pad-texture-repeat-val'),
  basePadTextureRotation: document.getElementById('base-pad-texture-rotation'),
  basePadTextureRotationVal: document.getElementById('base-pad-texture-rotation-val'),
  basePadNormal: document.getElementById('base-pad-normal'),
  basePadNormalVal: document.getElementById('base-pad-normal-val'),
  basePadHue: document.getElementById('base-pad-hue'),
  basePadHueVal: document.getElementById('base-pad-hue-val'),
  basePadSat: document.getElementById('base-pad-sat'),
  basePadSatVal: document.getElementById('base-pad-sat-val'),
  basePadBright: document.getElementById('base-pad-bright'),
  basePadBrightVal: document.getElementById('base-pad-bright-val'),
  basePadMetalness: document.getElementById('base-pad-metalness'),
  basePadMetalnessVal: document.getElementById('base-pad-metalness-val'),
  basePadRoughness: document.getElementById('base-pad-roughness'),
  basePadRoughnessVal: document.getElementById('base-pad-roughness-val'),
  basePadReflect: document.getElementById('base-pad-reflect'),
  basePadReflectVal: document.getElementById('base-pad-reflect-val'),
  basePadEmissive: document.getElementById('base-pad-emissive'),
  basePadEmissiveVal: document.getElementById('base-pad-emissive-val'),
  basePadBevelSize: document.getElementById('base-pad-bevel-size'),
  basePadBevelSizeVal: document.getElementById('base-pad-bevel-size-val'),
  basePadBevelSegments: document.getElementById('base-pad-bevel-segments'),
  basePadBevelSegmentsVal: document.getElementById('base-pad-bevel-segments-val'),
  basePadFlatShading: document.getElementById('base-pad-flat-shading'),
  basePadFlatShadingVal: document.getElementById('base-pad-flat-shading-val'),
  basePadBorderOpacity: document.getElementById('base-pad-border-opacity'),
  basePadBorderOpacityVal: document.getElementById('base-pad-border-opacity-val'),
  basePadBorderBright: document.getElementById('base-pad-border-bright'),
  basePadBorderBrightVal: document.getElementById('base-pad-border-bright-val'),
  buildingLowLedOffset: document.getElementById('building-low-led-offset'),
  buildingLowLedOffsetVal: document.getElementById('building-low-led-offset-val'),
  buildingHighLedOffset: document.getElementById('building-high-led-offset'),
  buildingHighLedOffsetVal: document.getElementById('building-high-led-offset-val'),
  buildingVerticalLedLength: document.getElementById('building-vertical-led-length'),
  buildingVerticalLedLengthVal: document.getElementById('building-vertical-led-length-val'),
  buildingVerticalLedY: document.getElementById('building-vertical-led-y'),
  buildingVerticalLedYVal: document.getElementById('building-vertical-led-y-val'),
  buildingLowLedY: document.getElementById('building-low-led-y'),
  buildingLowLedYVal: document.getElementById('building-low-led-y-val'),
  buildingHighLedY: document.getElementById('building-high-led-y'),
  buildingHighLedYVal: document.getElementById('building-high-led-y-val'),
  buildingFacadeLedNormal: document.getElementById('building-facade-led-normal'),
  buildingFacadeLedNormalVal: document.getElementById('building-facade-led-normal-val'),
  buildingFacadeLedX: document.getElementById('building-facade-led-x'),
  buildingFacadeLedXVal: document.getElementById('building-facade-led-x-val'),
  buildingFacadeLedY: document.getElementById('building-facade-led-y'),
  buildingFacadeLedYVal: document.getElementById('building-facade-led-y-val'),
  buildingFacadeLedZ: document.getElementById('building-facade-led-z'),
  buildingFacadeLedZVal: document.getElementById('building-facade-led-z-val'),
  bridgeXOffset: document.getElementById('bridge-x-offset'),
  bridgeXOffsetVal: document.getElementById('bridge-x-offset-val'),
  bridgeZOffset: document.getElementById('bridge-z-offset'),
  bridgeZOffsetVal: document.getElementById('bridge-z-offset-val'),
  bridgeYOffset: document.getElementById('bridge-y-offset'),
  bridgeYOffsetVal: document.getElementById('bridge-y-offset-val'),
  bridgeSpanScale: document.getElementById('bridge-span-scale'),
  bridgeSpanScaleVal: document.getElementById('bridge-span-scale-val'),
  bridgeHeightScale: document.getElementById('bridge-height-scale'),
  bridgeHeightScaleVal: document.getElementById('bridge-height-scale-val'),
  bridgeDepthScale: document.getElementById('bridge-depth-scale'),
  bridgeDepthScaleVal: document.getElementById('bridge-depth-scale-val'),
  bridgeLowLedOffset: document.getElementById('bridge-low-led-offset'),
  bridgeLowLedOffsetVal: document.getElementById('bridge-low-led-offset-val'),
  bridgeHighLedOffset: document.getElementById('bridge-high-led-offset'),
  bridgeHighLedOffsetVal: document.getElementById('bridge-high-led-offset-val'),
  bridgeControls: document.getElementById('bridge-controls'),
  collisionPadding: document.getElementById('collision-padding'),
  collisionPaddingVal: document.getElementById('collision-padding-val'),
  mainBuildingCollisionPadding: document.getElementById('main-building-collision-padding'),
  mainBuildingCollisionPaddingVal: document.getElementById('main-building-collision-padding-val'),
  noclipEnabled: document.getElementById('noclip-enabled'),
  noclipEnabledVal: document.getElementById('noclip-enabled-val'),
  cameraMinHeight: document.getElementById('camera-min-height'),
  cameraMinHeightVal: document.getElementById('camera-min-height-val'),
  walkSpeed: document.getElementById('walk-speed'),
  walkSpeedVal: document.getElementById('walk-speed-val'),
  sprintSpeed: document.getElementById('sprint-speed'),
  sprintSpeedVal: document.getElementById('sprint-speed-val'),
  backwardSpeedScale: document.getElementById('backward-speed-scale'),
  backwardSpeedScaleVal: document.getElementById('backward-speed-scale-val'),
  strafeSpeedScale: document.getElementById('strafe-speed-scale'),
  strafeSpeedScaleVal: document.getElementById('strafe-speed-scale-val'),
  diagonalSpeedScale: document.getElementById('diagonal-speed-scale'),
  diagonalSpeedScaleVal: document.getElementById('diagonal-speed-scale-val'),
  verticalSpeed: document.getElementById('vertical-speed'),
  verticalSpeedVal: document.getElementById('vertical-speed-val'),
  movementAccel: document.getElementById('movement-accel'),
  movementAccelVal: document.getElementById('movement-accel-val'),
  movementDecel: document.getElementById('movement-decel'),
  movementDecelVal: document.getElementById('movement-decel-val'),
  walkBob: document.getElementById('walk-bob'),
  walkBobVal: document.getElementById('walk-bob-val'),
  runBob: document.getElementById('run-bob'),
  runBobVal: document.getElementById('run-bob-val'),
  strafeBobScale: document.getElementById('strafe-bob-scale'),
  strafeBobScaleVal: document.getElementById('strafe-bob-scale-val'),
  backwardBobScale: document.getElementById('backward-bob-scale'),
  backwardBobScaleVal: document.getElementById('backward-bob-scale-val'),
  walkStepRate: document.getElementById('walk-step-rate'),
  walkStepRateVal: document.getElementById('walk-step-rate-val'),
  runStepRate: document.getElementById('run-step-rate'),
  runStepRateVal: document.getElementById('run-step-rate-val'),
  stepSnap: document.getElementById('step-snap'),
  stepSnapVal: document.getElementById('step-snap-val'),
  movementSway: document.getElementById('movement-sway'),
  movementSwayVal: document.getElementById('movement-sway-val'),
  movementRoll: document.getElementById('movement-roll'),
  movementRollVal: document.getElementById('movement-roll-val'),
  strafeLean: document.getElementById('strafe-lean'),
  strafeLeanVal: document.getElementById('strafe-lean-val'),
  headMotionSmoothing: document.getElementById('head-motion-smoothing'),
  headMotionSmoothingVal: document.getElementById('head-motion-smoothing-val'),
  mouseSensitivity: document.getElementById('mouse-sensitivity'),
  mouseSensitivityVal: document.getElementById('mouse-sensitivity-val'),
  runnerBodyLight: document.getElementById('runner-body-light'),
  runnerBodyLightVal: document.getElementById('runner-body-light-val'),
  runnerLineLight: document.getElementById('runner-line-light'),
  runnerLineLightVal: document.getElementById('runner-line-light-val'),
  runnerKeyLight: document.getElementById('runner-key-light'),
  runnerKeyLightVal: document.getElementById('runner-key-light-val'),
  runnerRimLight: document.getElementById('runner-rim-light'),
  runnerRimLightVal: document.getElementById('runner-rim-light-val'),
  runnerFillLight: document.getElementById('runner-fill-light'),
  runnerFillLightVal: document.getElementById('runner-fill-light-val'),
  runnerLedBrightness: document.getElementById('runner-led-brightness'),
  runnerLedBrightnessVal: document.getElementById('runner-led-brightness-val'),
  runnerLedBloom: document.getElementById('runner-led-bloom'),
  runnerLedBloomVal: document.getElementById('runner-led-bloom-val'),
  runnerBeatPulseEnabled: document.getElementById('runner-beat-pulse-enabled'),
  runnerBeatPulseEnabledVal: document.getElementById('runner-beat-pulse-enabled-val'),
  runnerBeatPulseBpm: document.getElementById('runner-beat-pulse-bpm'),
  runnerBeatPulseBpmVal: document.getElementById('runner-beat-pulse-bpm-val'),
  runnerBeatPulseOffset: document.getElementById('runner-beat-pulse-offset'),
  runnerBeatPulseOffsetVal: document.getElementById('runner-beat-pulse-offset-val'),
  runnerBeatPulseIntensity: document.getElementById('runner-beat-pulse-intensity'),
  runnerBeatPulseIntensityVal: document.getElementById('runner-beat-pulse-intensity-val'),
  runnerBeatPulseDecay: document.getElementById('runner-beat-pulse-decay'),
  runnerBeatPulseDecayVal: document.getElementById('runner-beat-pulse-decay-val'),
  runnerBeatPulseDivision: document.getElementById('runner-beat-pulse-division'),
  runnerBeatPulseDivisionVal: document.getElementById('runner-beat-pulse-division-val'),
  runnerMaterialReflect: document.getElementById('runner-material-reflect'),
  runnerMaterialReflectVal: document.getElementById('runner-material-reflect-val'),
  runnerMaterialMetalness: document.getElementById('runner-material-metalness'),
  runnerMaterialMetalnessVal: document.getElementById('runner-material-metalness-val'),
  runnerMaterialRoughness: document.getElementById('runner-material-roughness'),
  runnerMaterialRoughnessVal: document.getElementById('runner-material-roughness-val'),
  runnerFloorReflection: document.getElementById('runner-floor-reflection'),
  runnerFloorReflectionVal: document.getElementById('runner-floor-reflection-val'),
  runnerFloorReflectionScale: document.getElementById('runner-floor-reflection-scale'),
  runnerFloorReflectionScaleVal: document.getElementById('runner-floor-reflection-scale-val'),
  runnerShadowSoftness: document.getElementById('runner-shadow-softness'),
  runnerShadowSoftnessVal: document.getElementById('runner-shadow-softness-val'),
  runnerShadowPulse: document.getElementById('runner-shadow-pulse'),
  runnerShadowPulseVal: document.getElementById('runner-shadow-pulse-val'),
  runnerShadowCyan: document.getElementById('runner-shadow-cyan'),
  runnerShadowCyanVal: document.getElementById('runner-shadow-cyan-val'),
  runnerShadowOffsetX: document.getElementById('runner-shadow-offset-x'),
  runnerShadowOffsetXVal: document.getElementById('runner-shadow-offset-x-val'),
  runnerShadowOffsetZ: document.getElementById('runner-shadow-offset-z'),
  runnerShadowOffsetZVal: document.getElementById('runner-shadow-offset-z-val'),
  runnerKeyLightY: document.getElementById('runner-key-light-y'),
  runnerKeyLightYVal: document.getElementById('runner-key-light-y-val'),
  runnerKeyLightZ: document.getElementById('runner-key-light-z'),
  runnerKeyLightZVal: document.getElementById('runner-key-light-z-val'),
  runnerRimLightX: document.getElementById('runner-rim-light-x'),
  runnerRimLightXVal: document.getElementById('runner-rim-light-x-val'),
  runnerFillLightY: document.getElementById('runner-fill-light-y'),
  runnerFillLightYVal: document.getElementById('runner-fill-light-y-val'),
  runnerScale: document.getElementById('runner-scale'),
  runnerScaleVal: document.getElementById('runner-scale-val'),
  runnerAnimationSpeed: document.getElementById('runner-animation-speed'),
  runnerAnimationSpeedVal: document.getElementById('runner-animation-speed-val'),
  runnerWalkSpeed: document.getElementById('runner-walk-speed'),
  runnerWalkSpeedVal: document.getElementById('runner-walk-speed-val'),
  runnerStrideSync: document.getElementById('runner-stride-sync'),
  runnerStrideSyncVal: document.getElementById('runner-stride-sync-val'),
  sideBuildingBrightness: document.getElementById('side-building-brightness'),
  sideBuildingBrightnessVal: document.getElementById('side-building-brightness-val'),
  sideBuildingHue: document.getElementById('side-building-hue'),
  sideBuildingHueVal: document.getElementById('side-building-hue-val'),
  sideBuildingMetalness: document.getElementById('side-building-metalness'),
  sideBuildingMetalnessVal: document.getElementById('side-building-metalness-val'),
  sideBuildingRoughness: document.getElementById('side-building-roughness'),
  sideBuildingRoughnessVal: document.getElementById('side-building-roughness-val'),
  sideBuildingReflect: document.getElementById('side-building-reflect'),
  sideBuildingReflectVal: document.getElementById('side-building-reflect-val'),
  sideBuildingEmissive: document.getElementById('side-building-emissive'),
  sideBuildingEmissiveVal: document.getElementById('side-building-emissive-val'),
  sideBuildingWidthScale: document.getElementById('side-building-width-scale'),
  sideBuildingWidthScaleVal: document.getElementById('side-building-width-scale-val'),
  sideBuildingDepthScale: document.getElementById('side-building-depth-scale'),
  sideBuildingDepthScaleVal: document.getElementById('side-building-depth-scale-val'),
  sideBuildingSpacingScale: document.getElementById('side-building-spacing-scale'),
  sideBuildingSpacingScaleVal: document.getElementById('side-building-spacing-scale-val'),
  sideBuildingScale: document.getElementById('side-building-height-scale'),
  sideBuildingScaleVal: document.getElementById('side-building-height-scale-val'),
  sideBuildingBasePadScale: document.getElementById('side-building-base-pad-scale'),
  sideBuildingBasePadScaleVal: document.getElementById('side-building-base-pad-scale-val'),
  sideBuildingBasePadXScale: document.getElementById('side-building-base-pad-x-scale'),
  sideBuildingBasePadXScaleVal: document.getElementById('side-building-base-pad-x-scale-val'),
  sideBuildingBasePadY: document.getElementById('side-building-base-pad-y'),
  sideBuildingBasePadYVal: document.getElementById('side-building-base-pad-y-val'),
  sideBuildingBasePadThickness: document.getElementById('side-building-base-pad-thickness'),
  sideBuildingBasePadThicknessVal: document.getElementById('side-building-base-pad-thickness-val'),
  sideBuildingBasePadCut: document.getElementById('side-building-base-pad-cut'),
  sideBuildingBasePadCutVal: document.getElementById('side-building-base-pad-cut-val'),
  sideBuildingBasePadRadius: document.getElementById('side-building-base-pad-radius'),
  sideBuildingBasePadRadiusVal: document.getElementById('side-building-base-pad-radius-val'),
  mainBuildingBrightness: document.getElementById('main-building-brightness'),
  mainBuildingBrightnessVal: document.getElementById('main-building-brightness-val'),
  mainBuildingHue: document.getElementById('main-building-hue'),
  mainBuildingHueVal: document.getElementById('main-building-hue-val'),
  mainBuildingSaturation: document.getElementById('main-building-saturation'),
  mainBuildingSaturationVal: document.getElementById('main-building-saturation-val'),
  mainBuildingMetalness: document.getElementById('main-building-metalness'),
  mainBuildingMetalnessVal: document.getElementById('main-building-metalness-val'),
  mainBuildingRoughness: document.getElementById('main-building-roughness'),
  mainBuildingRoughnessVal: document.getElementById('main-building-roughness-val'),
  mainBuildingReflect: document.getElementById('main-building-reflect'),
  mainBuildingReflectVal: document.getElementById('main-building-reflect-val'),
  mainBuildingEmissive: document.getElementById('main-building-emissive'),
  mainBuildingEmissiveVal: document.getElementById('main-building-emissive-val'),
  mainBuildingWidthScale: document.getElementById('main-building-width-scale'),
  mainBuildingWidthScaleVal: document.getElementById('main-building-width-scale-val'),
  mainBuildingDepthScale: document.getElementById('main-building-depth-scale'),
  mainBuildingDepthScaleVal: document.getElementById('main-building-depth-scale-val'),
  mainBuildingZ: document.getElementById('main-building-z'),
  mainBuildingZVal: document.getElementById('main-building-z-val'),
  mainBuildingY: document.getElementById('main-building-y'),
  mainBuildingYVal: document.getElementById('main-building-y-val'),
  mainBuildingScale: document.getElementById('main-building-height-scale'),
  mainBuildingScaleVal: document.getElementById('main-building-height-scale-val'),
  mainBuildingBasePadScale: document.getElementById('main-building-base-pad-scale'),
  mainBuildingBasePadScaleVal: document.getElementById('main-building-base-pad-scale-val'),
  mainBuildingBasePadXScale: document.getElementById('main-building-base-pad-x-scale'),
  mainBuildingBasePadXScaleVal: document.getElementById('main-building-base-pad-x-scale-val'),
  mainBuildingBasePadZScale: document.getElementById('main-building-base-pad-z-scale'),
  mainBuildingBasePadZScaleVal: document.getElementById('main-building-base-pad-z-scale-val'),
  mainBuildingBasePadY: document.getElementById('main-building-base-pad-y'),
  mainBuildingBasePadYVal: document.getElementById('main-building-base-pad-y-val'),
  mainBuildingBasePadThickness: document.getElementById('main-building-base-pad-thickness'),
  mainBuildingBasePadThicknessVal: document.getElementById('main-building-base-pad-thickness-val'),
  mainBuildingBasePadCut: document.getElementById('main-building-base-pad-cut'),
  mainBuildingBasePadCutVal: document.getElementById('main-building-base-pad-cut-val'),
  mainBuildingBasePadRadius: document.getElementById('main-building-base-pad-radius'),
  mainBuildingBasePadRadiusVal: document.getElementById('main-building-base-pad-radius-val'),
  mainBuildingLedBrightness: document.getElementById('main-building-led-brightness'),
  mainBuildingLedBrightnessVal: document.getElementById('main-building-led-brightness-val'),
  mainBuildingLedThickness: document.getElementById('main-building-led-thickness'),
  mainBuildingLedThicknessVal: document.getElementById('main-building-led-thickness-val'),
  mainBuildingLedDistance: document.getElementById('main-building-led-distance'),
  mainBuildingLedDistanceVal: document.getElementById('main-building-led-distance-val'),
  mainBuildingHorizontalLedDistance: document.getElementById('main-building-horizontal-led-distance'),
  mainBuildingHorizontalLedDistanceVal: document.getElementById('main-building-horizontal-led-distance-val'),
  mainBuildingHorizontalLedThickness: document.getElementById('main-building-horizontal-led-thickness'),
  mainBuildingHorizontalLedThicknessVal: document.getElementById('main-building-horizontal-led-thickness-val'),
  mainBuildingHorizontalLedRadius: document.getElementById('main-building-horizontal-led-radius'),
  mainBuildingHorizontalLedRadiusVal: document.getElementById('main-building-horizontal-led-radius-val'),
  mainBuildingLedHue: document.getElementById('main-building-led-hue'),
  mainBuildingLedHueVal: document.getElementById('main-building-led-hue-val'),
  mainBuildingLowLedOffset: document.getElementById('main-building-low-led-offset'),
  mainBuildingLowLedOffsetVal: document.getElementById('main-building-low-led-offset-val'),
  mainBuildingHighLedOffset: document.getElementById('main-building-high-led-offset'),
  mainBuildingHighLedOffsetVal: document.getElementById('main-building-high-led-offset-val'),
  mainBuildingVerticalLedLength: document.getElementById('main-building-vertical-led-length'),
  mainBuildingVerticalLedLengthVal: document.getElementById('main-building-vertical-led-length-val'),
  mainBuildingVerticalLedY: document.getElementById('main-building-vertical-led-y'),
  mainBuildingVerticalLedYVal: document.getElementById('main-building-vertical-led-y-val'),
  mainBuildingLowLedY: document.getElementById('main-building-low-led-y'),
  mainBuildingLowLedYVal: document.getElementById('main-building-low-led-y-val'),
  mainBuildingHighLedY: document.getElementById('main-building-high-led-y'),
  mainBuildingHighLedYVal: document.getElementById('main-building-high-led-y-val'),
  mainLedBrightnessUi: document.getElementById('main-led-brightness-ui'),
  mainLedBrightnessUiVal: document.getElementById('main-led-brightness-ui-val'),
  mainLedHueUi: document.getElementById('main-led-hue-ui'),
  mainLedHueUiVal: document.getElementById('main-led-hue-ui-val'),
  mainLedVerticalDistanceUi: document.getElementById('main-led-vertical-distance-ui'),
  mainLedVerticalDistanceUiVal: document.getElementById('main-led-vertical-distance-ui-val'),
  mainLedThicknessUi: document.getElementById('main-led-thickness-ui'),
  mainLedThicknessUiVal: document.getElementById('main-led-thickness-ui-val'),
  mainLedVerticalLengthUi: document.getElementById('main-led-vertical-length-ui'),
  mainLedVerticalLengthUiVal: document.getElementById('main-led-vertical-length-ui-val'),
  mainLedVerticalYUi: document.getElementById('main-led-vertical-y-ui'),
  mainLedVerticalYUiVal: document.getElementById('main-led-vertical-y-ui-val'),
  mainLedHorizontalDistanceUi: document.getElementById('main-led-horizontal-distance-ui'),
  mainLedHorizontalDistanceUiVal: document.getElementById('main-led-horizontal-distance-ui-val'),
  mainLedHorizontalThicknessUi: document.getElementById('main-led-horizontal-thickness-ui'),
  mainLedHorizontalThicknessUiVal: document.getElementById('main-led-horizontal-thickness-ui-val'),
  mainLedHorizontalRadiusUi: document.getElementById('main-led-horizontal-radius-ui'),
  mainLedHorizontalRadiusUiVal: document.getElementById('main-led-horizontal-radius-ui-val'),
  mainLedLowOffsetUi: document.getElementById('main-led-low-offset-ui'),
  mainLedLowOffsetUiVal: document.getElementById('main-led-low-offset-ui-val'),
  mainLedLowYUi: document.getElementById('main-led-low-y-ui'),
  mainLedLowYUiVal: document.getElementById('main-led-low-y-ui-val'),
  mainLedHighOffsetUi: document.getElementById('main-led-high-offset-ui'),
  mainLedHighOffsetUiVal: document.getElementById('main-led-high-offset-ui-val'),
  mainLedHighYUi: document.getElementById('main-led-high-y-ui'),
  mainLedHighYUiVal: document.getElementById('main-led-high-y-ui-val'),
  mainFacadeLedBrightnessUi: document.getElementById('main-facade-led-brightness-ui'),
  mainFacadeLedBrightnessUiVal: document.getElementById('main-facade-led-brightness-ui-val'),
  mainFacadeLedNormalUi: document.getElementById('main-facade-led-normal-ui'),
  mainFacadeLedNormalUiVal: document.getElementById('main-facade-led-normal-ui-val'),
  mainFacadeLedXUi: document.getElementById('main-facade-led-x-ui'),
  mainFacadeLedXUiVal: document.getElementById('main-facade-led-x-ui-val'),
  mainFacadeLedYUi: document.getElementById('main-facade-led-y-ui'),
  mainFacadeLedYUiVal: document.getElementById('main-facade-led-y-ui-val'),
  mainFacadeLedZUi: document.getElementById('main-facade-led-z-ui'),
  mainFacadeLedZUiVal: document.getElementById('main-facade-led-z-ui-val'),
  mainFacadeLedThicknessUi: document.getElementById('main-facade-led-thickness-ui'),
  mainFacadeLedThicknessUiVal: document.getElementById('main-facade-led-thickness-ui-val'),
  mainFacadeLedSegmentControls: Array.from({ length: 6 }, (_, index) => ({
    u: document.getElementById(`main-facade-led-seg-${index + 1}-u-ui`),
    uVal: document.getElementById(`main-facade-led-seg-${index + 1}-u-ui-val`),
    y: document.getElementById(`main-facade-led-seg-${index + 1}-y-ui`),
    yVal: document.getElementById(`main-facade-led-seg-${index + 1}-y-ui-val`),
    normal: document.getElementById(`main-facade-led-seg-${index + 1}-normal-ui`),
    normalVal: document.getElementById(`main-facade-led-seg-${index + 1}-normal-ui-val`),
  })),
  performanceMode: document.getElementById('performance-mode'),
  renderResolution: document.getElementById('render-resolution'),
  renderResolutionVal: document.getElementById('render-resolution-val'),
  aaMode: document.getElementById('aa-mode'),
  bloomEnabled: document.getElementById('bloom-enabled'),
  bloomStrength: document.getElementById('bloom-strength'),
  bloomVal: document.getElementById('bloom-val'),
  bloomRadius: document.getElementById('bloom-radius'),
  bloomRadiusVal: document.getElementById('bloom-radius-val'),
  bloomThreshold: document.getElementById('bloom-threshold'),
  bloomThresholdVal: document.getElementById('bloom-threshold-val'),
  bloomQuality: document.getElementById('bloom-quality'),
  bloomQualityVal: document.getElementById('bloom-quality-val'),
  pixelRatio: document.getElementById('pixel-ratio'),
  pixelRatioVal: document.getElementById('pixel-ratio-val'),
  fsrPreset: document.getElementById('fsr-preset'),
  fsrUpscaleEnabled: document.getElementById('fsr-upscale-enabled'),
  fsrInternalScale: document.getElementById('fsr-internal-scale'),
  fsrInternalScaleVal: document.getElementById('fsr-internal-scale-val'),
  fsrSharpness: document.getElementById('fsr-sharpness'),
  fsrSharpnessVal: document.getElementById('fsr-sharpness-val'),
  runFsrBenchmark: document.getElementById('run-fsr-benchmark'),
  fsrBenchmarkResults: document.getElementById('fsr-benchmark-results'),
  wireframeEnabled: document.getElementById('wireframe-enabled'),
  wireframeEnabledVal: document.getElementById('wireframe-enabled-val'),
  wireframeDelay: document.getElementById('wireframe-delay'),
  wireframeDelayVal: document.getElementById('wireframe-delay-val'),
  wireframeFade: document.getElementById('wireframe-fade'),
  wireframeFadeVal: document.getElementById('wireframe-fade-val'),
  wireframeDensity: document.getElementById('wireframe-density'),
  wireframeDensityVal: document.getElementById('wireframe-density-val'),
  wireframeOpacity: document.getElementById('wireframe-opacity'),
  wireframeOpacityVal: document.getElementById('wireframe-opacity-val'),
  wireframeBackplate: document.getElementById('wireframe-backplate'),
  wireframeBackplateVal: document.getElementById('wireframe-backplate-val'),
  musicFxEnabled: document.getElementById('music-fx-enabled'),
  musicFxEnabledVal: document.getElementById('music-fx-enabled-val'),
  musicFxMix: document.getElementById('music-fx-mix'),
  musicFxMixVal: document.getElementById('music-fx-mix-val'),
  musicFxCrusher: document.getElementById('music-fx-crusher'),
  musicFxCrusherVal: document.getElementById('music-fx-crusher-val'),
  musicFxBitDepth: document.getElementById('music-fx-bit-depth'),
  musicFxBitDepthVal: document.getElementById('music-fx-bit-depth-val'),
  musicFxHighpass: document.getElementById('music-fx-highpass'),
  musicFxHighpassVal: document.getElementById('music-fx-highpass-val'),
  musicFxLowpass: document.getElementById('music-fx-lowpass'),
  musicFxLowpassVal: document.getElementById('music-fx-lowpass-val'),
  musicFxDistortion: document.getElementById('music-fx-distortion'),
  musicFxDistortionVal: document.getElementById('music-fx-distortion-val'),
  musicFxTelephone: document.getElementById('music-fx-telephone'),
  musicFxTelephoneVal: document.getElementById('music-fx-telephone-val'),
  musicFxWobble: document.getElementById('music-fx-wobble'),
  musicFxWobbleVal: document.getElementById('music-fx-wobble-val'),
  musicFxNoise: document.getElementById('music-fx-noise'),
  musicFxNoiseVal: document.getElementById('music-fx-noise-val'),
  resetCameraHeight: document.getElementById('reset-camera-height'),
  playerSpawnVal: document.getElementById('player-spawn-val'),
  saveLiveSpawn: document.getElementById('save-live-spawn'),
  resetPlayerSpawn: document.getElementById('reset-player-spawn'),
  startPositionLiveVal: document.getElementById('start-position-live-val'),
  startPositionSavedVal: document.getElementById('start-position-saved-val'),
  saveStartPosition: document.getElementById('save-start-position'),
  goStartPosition: document.getElementById('go-start-position'),
  droneIntroFlight: document.getElementById('drone-intro-flight'),
  };
}

export const DEFAULT_PRODUCTION_PANEL = 'bloom-fx';
export const PRODUCTION_CONTROL_PANELS = new Set([
  'movement',
  'character',
  'surface-reflections',
  'bloom-fx',
  'led-glow-fx',
  'central-building-leds',
  'wireframe-fx',
  'audio-fx',
  'atmosphere-fx',
  'performance-fx',
]);
export const PRODUCTION_LIVE_CONTROL_SELECTOR = Array.from(PRODUCTION_CONTROL_PANELS).flatMap((panel) => [
  `#hud-controls .control-panel[data-panel="${panel}"] input[type="range"]`,
  `#hud-controls .control-panel[data-panel="${panel}"] input[type="checkbox"]`,
  `#hud-controls .control-panel[data-panel="${panel}"] select`,
]).join(',');

export const SKY_FAST_CONTROL_IDS = new Set([
  'sky-choice',
  'sky-quality',
  'sky-brightness',
  'sky-hue',
  'sky-cloud-contrast',
  'sky-storm-frequency',
  'sky-storm-intensity',
  'sky-storm-size',
  'sky-storm-cloud-threshold',
  'sky-storm-band',
  'sky-storm-veil',
]);
export const POST_FAST_CONTROL_IDS = new Set([
  'performance-mode',
  'render-resolution',
  'aa-mode',
  'bloom-enabled',
  'bloom-strength',
  'bloom-radius',
  'bloom-threshold',
  'bloom-quality',
  'pixel-ratio',
  'fsr-preset',
  'fsr-upscale-enabled',
  'fsr-internal-scale',
  'fsr-sharpness',
]);
export const WIREFRAME_FAST_CONTROL_IDS = new Set([
  'wireframe-enabled',
  'wireframe-delay',
  'wireframe-fade',
  'wireframe-density',
  'wireframe-opacity',
  'wireframe-backplate',
]);
export const AUDIO_FX_FAST_CONTROL_IDS = new Set([
  'music-fx-enabled',
  'music-fx-mix',
  'music-fx-crusher',
  'music-fx-bit-depth',
  'music-fx-highpass',
  'music-fx-lowpass',
  'music-fx-distortion',
  'music-fx-telephone',
  'music-fx-wobble',
  'music-fx-noise',
]);
export const MOVEMENT_FAST_CONTROL_IDS = new Set([
  'collision-padding',
  'main-building-collision-padding',
  'noclip-enabled',
  'camera-min-height',
  'walk-speed',
  'sprint-speed',
  'backward-speed-scale',
  'strafe-speed-scale',
  'diagonal-speed-scale',
  'vertical-speed',
  'movement-accel',
  'movement-decel',
  'walk-bob',
  'run-bob',
  'strafe-bob-scale',
  'backward-bob-scale',
  'walk-step-rate',
  'run-step-rate',
  'step-snap',
  'movement-sway',
  'movement-roll',
  'strafe-lean',
  'head-motion-smoothing',
  'mouse-sensitivity',
]);
export const CHARACTER_FAST_CONTROL_IDS = new Set([
  'runner-body-light',
  'runner-line-light',
  'runner-key-light',
  'runner-rim-light',
  'runner-fill-light',
  'runner-led-brightness',
  'runner-led-bloom',
  'runner-beat-pulse-enabled',
  'runner-beat-pulse-bpm',
  'runner-beat-pulse-offset',
  'runner-beat-pulse-intensity',
  'runner-beat-pulse-decay',
  'runner-beat-pulse-division',
  'runner-material-reflect',
  'runner-material-metalness',
  'runner-material-roughness',
  'runner-floor-reflection',
  'runner-floor-reflection-scale',
  'runner-shadow-softness',
  'runner-shadow-pulse',
  'runner-shadow-cyan',
  'runner-shadow-offset-x',
  'runner-shadow-offset-z',
  'runner-key-light-y',
  'runner-key-light-z',
  'runner-rim-light-x',
  'runner-fill-light-y',
  'runner-scale',
  'runner-animation-speed',
  'runner-walk-speed',
  'runner-stride-sync',
]);
export const LIGHT_FAST_CONTROL_IDS = new Set(['ambient-light', 'key-light', 'exposure']);
export const HEX_RUNTIME_FAST_CONTROL_IDS = new Set([
  'hex-offset',
  'hex-radius',
  'hex-drop-delay',
  'hex-drop-speed',
  'hex-recovery',
  'tile-hit-light',
  'player-tile-light',
]);
export const ROAD_MATERIAL_FAST_CONTROL_IDS = new Set([
  'road-normal',
  'road-light',
  'road-reflect',
  'road-building-reflect',
  'road-metalness',
  'road-roughness',
  'road-hue',
  'road-sat',
  'road-bright',
]);
export const BUILDING_MATERIAL_FAST_CONTROL_IDS = new Set([
  'side-building-brightness',
  'side-building-hue',
  'side-building-metalness',
  'side-building-roughness',
  'side-building-reflect',
  'side-building-emissive',
  'main-building-brightness',
  'main-building-hue',
  'main-building-metalness',
  'main-building-roughness',
  'main-building-reflect',
  'main-building-emissive',
]);
export const BASE_PAD_MATERIAL_FAST_CONTROL_IDS = new Set([
  'base-pad-texture-mode',
  'base-pad-texture-repeat',
  'base-pad-texture-rotation',
  'base-pad-normal',
  'base-pad-hue',
  'base-pad-sat',
  'base-pad-bright',
  'base-pad-metalness',
  'base-pad-roughness',
  'base-pad-reflect',
  'base-pad-emissive',
  'base-pad-flat-shading',
  'base-pad-border-opacity',
  'base-pad-border-bright',
]);
export const BOUNDARY_ERROR_FAST_CONTROL_IDS = new Set([
  'road-boundary-collision-enabled',
  'road-boundary-collision-margin',
  'road-boundary-camera-lead',
  'road-boundary-pulse-strength',
  'boundary-error-visible',
  'boundary-error-size',
  'boundary-error-anchor',
  'boundary-error-animation',
  'boundary-error-duration',
  'boundary-error-glitch',
  'boundary-error-render-mode',
  'boundary-error-floor-light-enabled',
  'boundary-error-floor-light-radius',
  'boundary-error-floor-light-intensity',
  'boundary-error-floor-light-opacity',
  'boundary-error-floor-light-hue',
  'boundary-error-floor-light-y',
  'boundary-error-floor-light-softness',
]);
